package ch.zhaw.stellarcompass.repository;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import ch.zhaw.stellarcompass.model.User;
import ch.zhaw.stellarcompass.model.UserRole;

@SpringBootTest
class UserRepositoryTest {
    
    @Autowired
    private UserRepository userRepository;

    @Test
    void testSaveAndFindUser() {
        // 1. arrange: Create User
        String  email = "test@stellar.com";
        // delete, if it is already ther because of previous test runs (cleanup)
        userRepository.findByEmail(email).ifPresent(user-> userRepository.delete(user));

        User user = new User(email, "Test User", UserRole.STUDENT);
        user.setAuth0Id("auth0|123456");

        // 2. Act: save User
        User savedUser = userRepository.save(user);

        // 3. Assert: verify User is saved and can be found
        assertNotNull(savedUser.getId(), "ID should be generated by MongoDB");
        
        User foundUser = userRepository.findByEmail(email).orElse(null);
        assertNotNull(foundUser, "User should be found in the DB");
        assertEquals("Test User", foundUser.getName());
        assertEquals(UserRole.STUDENT, foundUser.getRole());

        // Cleanup
        userRepository.delete(savedUser);
    }
    @ParameterizedTest
    @EnumSource(UserRole.class) // Test all enum values like STUDENT, Mentor, Admin
    void testSaveUserWithRole(UserRole role){
        // Arrange
        String email = "test-" + role + "@stellar.com";
        User user = new User(email, "Role Tester", role);

        // Act
        User savedUser = userRepository.save(user);

        // Assert
        assertNotNull(savedUser.getId());
        assertEquals(role, savedUser.getRole());

        // Cleanup
        userRepository.delete(savedUser);
    }
}
