package ch.zhaw.stellarcompass.repository;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DuplicateKeyException;

import ch.zhaw.stellarcompass.model.User;
import ch.zhaw.stellarcompass.model.UserRole;

@SpringBootTest
class UserRepositoryTest {
    
    @Autowired
    private UserRepository userRepository;

    private User testStudent;
    private User testMentor;
    private User testAdmin;

    @BeforeEach
    void setUp() {
        // Clean up before each test
        userRepository.deleteAll();

        // Setup test users
        testStudent = new User("student@stellar.com", "Test Student", UserRole.STUDENT);
        testStudent.setAuth0Id("auth0|student123");

        testMentor = new User("mentor@stellar.com", "Test Mentor", UserRole.MENTOR);
        testMentor.setAuth0Id("auth0|mentor456");

        testAdmin = new User("admin@stellar.com", "Test Admin", UserRole.ADMIN);
        testAdmin.setAuth0Id("auth0|admin789");
    }

    @AfterEach
    void cleanup() {
        // Clean up after each test
        userRepository.deleteAll();
    }

    // ==================== Basic CRUD Tests ====================

    @Test
    void testSaveAndFindUser() {
        // Act: save User
        User savedUser = userRepository.save(testStudent);

        // Assert: verify User is saved and can be found
        assertNotNull(savedUser.getId(), "ID should be generated by MongoDB");
        
        User foundUser = userRepository.findByEmail("student@stellar.com").orElse(null);
        assertNotNull(foundUser, "User should be found in the DB");
        assertEquals("Test Student", foundUser.getName());
        assertEquals(UserRole.STUDENT, foundUser.getRole());
        assertEquals("auth0|student123", foundUser.getAuth0Id());
    }

    @ParameterizedTest
    @EnumSource(UserRole.class) // Test all enum values: STUDENT, MENTOR, ADMIN
    void testSaveUserWithRole(UserRole role) {
        // Arrange
        String email = "test-" + role + "@stellar.com";
        User user = new User(email, "Role Tester", role);

        // Act
        User savedUser = userRepository.save(user);

        // Assert
        assertNotNull(savedUser.getId());
        assertEquals(role, savedUser.getRole());
        assertEquals(email, savedUser.getEmail());
    }

    // ==================== Find By Email Tests ====================

    @Test
    void testFindByEmail_Success() {
        // Arrange
        userRepository.save(testStudent);

        // Act
        Optional<User> foundUser = userRepository.findByEmail("student@stellar.com");

        // Assert
        assertTrue(foundUser.isPresent(), "User should be found");
        assertEquals("Test Student", foundUser.get().getName());
    }

    @Test
    void testFindByEmail_NotFound() {
        // Act
        Optional<User> foundUser = userRepository.findByEmail("nonexistent@stellar.com");

        // Assert
        assertFalse(foundUser.isPresent(), "User should not be found");
    }

    @Test
    void testFindByEmail_CaseSensitive() {
        // Arrange
        userRepository.save(testStudent);

        // Act - Email in different case
        Optional<User> foundUser = userRepository.findByEmail("STUDENT@stellar.com");

        // Assert - MongoDB queries are case-sensitive by default
        assertFalse(foundUser.isPresent(), "Email search should be case-sensitive");
    }

    // ==================== Find By Auth0Id Tests ====================

    @Test
    void testFindByAuth0Id_Success() {
        // Arrange
        userRepository.save(testMentor);

        // Act
        Optional<User> foundUser = userRepository.findByAuth0Id("auth0|mentor456");

        // Assert
        assertTrue(foundUser.isPresent(), "User should be found by Auth0 ID");
        assertEquals("Test Mentor", foundUser.get().getName());
        assertEquals("mentor@stellar.com", foundUser.get().getEmail());
    }

    @Test
    void testFindByAuth0Id_NotFound() {
        // Act
        Optional<User> foundUser = userRepository.findByAuth0Id("auth0|nonexistent");

        // Assert
        assertFalse(foundUser.isPresent(), "User should not be found");
    }

    @Test
    void testFindByAuth0Id_FindsUserWithNullAuth0Id() {
        // Arrange - User without Auth0Id
        User userWithoutAuth0 = new User("noauth@stellar.com", "No Auth", UserRole.STUDENT);
        userRepository.save(userWithoutAuth0);

        // Act - Search for null Auth0Id
        Optional<User> foundUser = userRepository.findByAuth0Id(null);

        // Assert - MongoDB finds documents where the field is null
        assertTrue(foundUser.isPresent(), "Should find user with null Auth0Id");
        assertEquals("noauth@stellar.com", foundUser.get().getEmail());
        assertNull(foundUser.get().getAuth0Id(), "Auth0Id should be null");
    }

    @Test
    void testFindByAuth0Id_NullSearch_NoMatch() {
        // Arrange - All users have Auth0Id set
        userRepository.save(testStudent);
        userRepository.save(testMentor);

        // Act - Search for null Auth0Id when no user has it
        Optional<User> foundUser = userRepository.findByAuth0Id(null);

        // Assert
        assertFalse(foundUser.isPresent(), "Should not find user when all users have Auth0Id");
    }

    // ==================== Unique Constraint Tests ====================

    @Test
    void testSaveUser_DuplicateEmail_ThrowsException() {
        // Arrange
        userRepository.save(testStudent);
        User duplicateUser = new User("student@stellar.com", "Duplicate", UserRole.STUDENT);
        duplicateUser.setAuth0Id("auth0|different");

        // Act & Assert
        assertThrows(DuplicateKeyException.class, () -> {
            userRepository.save(duplicateUser);
        }, "Should throw DuplicateKeyException for duplicate email");
    }

    // ==================== Update Tests ====================

    @Test
    void testUpdateUser() {
        // Arrange
        User savedUser = userRepository.save(testStudent);
        String userId = savedUser.getId();

        // Act - Update user details
        savedUser.setName("Updated Student Name");
        savedUser.setRole(UserRole.MENTOR);
        savedUser.setMentorId("mentor-123");
        User updatedUser = userRepository.save(savedUser);

        // Assert
        assertEquals(userId, updatedUser.getId(), "ID should remain the same");
        assertEquals("Updated Student Name", updatedUser.getName());
        assertEquals(UserRole.MENTOR, updatedUser.getRole());
        assertEquals("mentor-123", updatedUser.getMentorId());

        // Verify from DB
        User foundUser = userRepository.findById(userId).orElse(null);
        assertNotNull(foundUser);
        assertEquals("Updated Student Name", foundUser.getName());
    }

    // ==================== Delete Tests ====================

    @Test
    void testDeleteUser() {
        // Arrange
        User savedUser = userRepository.save(testAdmin);
        String userId = savedUser.getId();

        // Act
        userRepository.delete(savedUser);

        // Assert
        Optional<User> foundUser = userRepository.findById(userId);
        assertFalse(foundUser.isPresent(), "User should be deleted");
    }

    @Test
    void testDeleteById() {
        // Arrange
        User savedUser = userRepository.save(testAdmin);
        String userId = savedUser.getId();

        // Act
        userRepository.deleteById(userId);

        // Assert
        Optional<User> foundUser = userRepository.findById(userId);
        assertFalse(foundUser.isPresent(), "User should be deleted");
    }

    // ==================== FindAll Tests ====================

    @Test
    void testFindAll_MultipleUsers() {
        // Arrange
        userRepository.save(testStudent);
        userRepository.save(testMentor);
        userRepository.save(testAdmin);

        // Act
        List<User> allUsers = userRepository.findAll();

        // Assert
        assertEquals(3, allUsers.size(), "Should find all 3 users");
    }

    @Test
    void testFindAll_EmptyRepository() {
        // Act
        List<User> allUsers = userRepository.findAll();

        // Assert
        assertTrue(allUsers.isEmpty(), "Repository should be empty");
    }

    // ==================== FindById Tests ====================

    @Test
    void testFindById_Success() {
        // Arrange
        User savedUser = userRepository.save(testStudent);
        String userId = savedUser.getId();

        // Act
        Optional<User> foundUser = userRepository.findById(userId);

        // Assert
        assertTrue(foundUser.isPresent(), "User should be found by ID");
        assertEquals("student@stellar.com", foundUser.get().getEmail());
    }

    @Test
    void testFindById_NotFound() {
        // Act
        Optional<User> foundUser = userRepository.findById("nonexistent-id");

        // Assert
        assertFalse(foundUser.isPresent(), "User should not be found");
    }

    // ==================== Exists Tests ====================

    @Test
    void testExistsById() {
        // Arrange
        User savedUser = userRepository.save(testMentor);
        String userId = savedUser.getId();

        // Act & Assert
        assertTrue(userRepository.existsById(userId), "User should exist");
        assertFalse(userRepository.existsById("nonexistent-id"), "User should not exist");
    }

    // ==================== Count Tests ====================

    @Test
    void testCount() {
        // Arrange
        userRepository.save(testStudent);
        userRepository.save(testMentor);

        // Act
        long count = userRepository.count();

        // Assert
        assertEquals(2, count, "Should count 2 users");
    }

    // ==================== MentorId Tests ====================

    @Test
    void testSaveUserWithMentorId() {
        // Arrange
        User mentor = userRepository.save(testMentor);
        testStudent.setMentorId(mentor.getId());

        // Act
        User savedStudent = userRepository.save(testStudent);

        // Assert
        assertEquals(mentor.getId(), savedStudent.getMentorId(), "MentorId should be set");

        // Verify from DB
        User foundStudent = userRepository.findByEmail("student@stellar.com").orElse(null);
        assertNotNull(foundStudent);
        assertEquals(mentor.getId(), foundStudent.getMentorId());
    }
}
